name: Build App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: "yarn"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Prepare dependencies
        run: yarn --frozen-lockfile
      - name: Install wine
        run: |
          sudo dpkg --add-architecture i386
          wget -nc https://dl.winehq.org/wine-builds/winehq.key
          sudo apt-key add winehq.key
          sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
          sudo apt update
          sudo apt install --install-recommends winehq-stable
      - name: Build page
        env:
          CI: false
        run: |
          yarn react:build
      - name: Build Windows x64 app
        run: yarn electron:build:win
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: dist/*.exe
